import React, { ReactNode } from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font';
import './globals.css';

interface RootLayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

const RootLayout: React.FC<RootLayoutProps> = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <head>
        {}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
      </head>
      <body className={inter.className as string}>{children}</body>
    </html>
  );
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
