import React from 'react';
import './globals.css';

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
      </head>
      <body>{children}</body>
    </html>
  );
};

const { Metadata } = require('next');

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;

